# Generated by Django 3.1.2 on 2020-10-21 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20201021_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 21, 16, 16, 19, 123892, tzinfo=utc)),
        ),
    ]
